- docker compose build --no-cache
- docker compose up
- docker compose run command-app bash
$ pip install library_name
$ pip freeze > requirements.txt
- docker compose exec command-app pip freeze > requirements.lock
