name: "infra preview & deploy"

on:
  push:
    branches:
      - 1-dev-env-and-pipeline
    paths:
      - .github/workflows/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TERRAFORM_VERSION: "1.7.0"
  PROJECT_ID: "generative-ai-app-426413"
  PROJECT_NAME: terraform-test
  SOURCE_REGION: "us-central1"
  BUCKET_NAME: "test-oshin-drone-destination-bucket"
  BUCKET_LOCATION: "asia-northeast1"

jobs:
  preview:
    name: "Preview"
    runs-on: ubuntu-latest
    outputs:
      TF_PLAN_EXITCODE: ${{ steps.plan.outputs.exitcode }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Terraform format
        run: |
          terraform fmt -check
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY }}"
      - name: Terraform init
        run: |
          terraform init -no-color
      - name: Terraform validate
        run: |
          terraform validate -no-color
      - name: Terraform plan
        continue-on-error: true
        id: plan
        run: |
          terraform plan \
            -var 'project_id=${{ env.PROJECT_ID }}' \
            -var 'project_name=${{ env.PROJECT_NAME }}' \
            -var 'source_region=${{ env.SOURCE_REGION }}' \
            -var 'bucket_name=${{ env.BUCKET_NAME }}' \
            -var 'bucket_location=${{ env.BUCKET_LOCATION }}' \
            -input=false \
            -no-color \
            -detailed-exitcode
      - name: Slack notify
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: 'C0804B4KTDK'
          payload: |
            {
              "attachments": [
                {
                  "blocks": [
                    {
                      "type": "header",
                      "text": {
                        "type": "plain_text",
                        "text": "Request for approve",
                        "emoji": true
                      }
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "${{ github.server_url }}/${{ github.repository }}/actions/run/${{ github.run_id }}"
                      }
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
